"""SQLite persistence for the deterministic engine (spec §13).

Phase 1 tables: documents, document_versions, sections, paragraphs, sentences, extraction_runs.
Phase 2: entities, entity_mentions. Phase 3: extraction_rules, observations, claims,
claim_evidence. Phase 4: study_characteristics, funders, funding_relationships, institutions,
authors, affiliations, author_affiliations. Phase 5: assessment_frameworks, assessment_criteria,
assessments. Phase 6: observation_qualifiers, claim_qualifiers. Phase 11: open_observations
(relation-bearing spans, isolated from claims). We use
``Base.metadata.create_all`` guarded by ``SCHEMA_VERSION`` rather than Alembic until the schema
stabilizes.
"""

from .schema import (
    AffiliationRow,
    AssessmentCriterionRow,
    AssessmentFrameworkRow,
    AssessmentRow,
    AuthorAffiliationRow,
    AuthorRow,
    Base,
    ClaimEvidenceRow,
    ClaimModifierRow,
    ClaimQualifierRow,
    ClaimRow,
    DocumentRow,
    DocumentVersionRow,
    EntityMentionRow,
    EntityModifierRow,
    EntityRow,
    ExtractionRuleRow,
    ExtractionRunRow,
    FunderRow,
    FundingRelationshipRow,
    InstitutionRow,
    ObservationQualifierRow,
    ObservationRow,
    OpenObservationRow,
    ParagraphRow,
    SectionRow,
    SentenceRow,
    StudyCharacteristicRow,
    load_document,
    persist_affiliations,
    persist_assessments,
    persist_document,
    persist_entities,
    persist_funding,
    persist_open_observations,
    persist_relations,
    persist_study,
)
from .session import default_db_path, get_engine, init_db, session_scope

__all__ = [
    "Base",
    "DocumentRow",
    "DocumentVersionRow",
    "EntityMentionRow",
    "EntityModifierRow",
    "EntityRow",
    "ExtractionRunRow",
    "ExtractionRuleRow",
    "ObservationRow",
    "ObservationQualifierRow",
    "OpenObservationRow",
    "ClaimRow",
    "ClaimEvidenceRow",
    "ClaimQualifierRow",
    "ClaimModifierRow",
    "StudyCharacteristicRow",
    "FunderRow",
    "FundingRelationshipRow",
    "InstitutionRow",
    "AuthorRow",
    "AffiliationRow",
    "AuthorAffiliationRow",
    "AssessmentFrameworkRow",
    "AssessmentCriterionRow",
    "AssessmentRow",
    "ParagraphRow",
    "SectionRow",
    "SentenceRow",
    "load_document",
    "persist_document",
    "persist_entities",
    "persist_relations",
    "persist_study",
    "persist_funding",
    "persist_open_observations",
    "persist_affiliations",
    "persist_assessments",
    "default_db_path",
    "get_engine",
    "init_db",
    "session_scope",
]
